"""investment transactions

Revision ID: 317e5ee29c2a
Revises: e10f91939057
Create Date: 2026-05-17 20:34:27.007140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '317e5ee29c2a'
down_revision: Union[str, None] = 'e10f91939057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='investment_transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_transactions_id'), 'investment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_investment_id'), 'investment_transactions', ['investment_id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_user_id'), 'investment_transactions', ['user_id'], unique=False)
    op.drop_column('investments', 'amount_invested')
    op.drop_column('investments', 'invested_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('invested_at', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('investments', sa.Column('amount_invested', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_investment_transactions_user_id'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_investment_id'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_id'), table_name='investment_transactions')
    op.drop_table('investment_transactions')
    # ### end Alembic commands ###
